version: '3.2'
services:

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    command: bin/app-start.sh
    environment:
      POSTGRESQL_HOST: db
      RAILS_ENV: development
      BUNDLE_GEMFILE: /app/Gemfile
      BUNDLE_JOBS: 2
      BUNDLE_PATH: /bundle
      EDITOR: vim
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - uploads:/app/public/uploads
      - bundle:/bundle
    ports:
      - $PORT:$PORT
      - $WEBPACK_PORT:$WEBPACK_PORT
    depends_on:
      - db
    links:
      - db

  # pgadmin4:
  #   image: 'thajeztah/pgadmin4'
  #   ports:
  #     - '5050:5050'
  #   depends_on:
  #     - db
  #   links:
  #     - db:postgres

volumes:
  data:
  uploads:
  bundle:

